-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', FILE.BOARD_ID, '/', FILE.FILE_ID, FILE.FILE_NAME, FILE.FILE_EXT) AS FILE_PATH
FROM (
    SELECT BOARD_ID, VIEWS FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1
) MAX_VIEW
INNER JOIN USED_GOODS_FILE FILE ON MAX_VIEW.BOARD_ID = FILE.BOARD_ID
ORDER BY FILE.FILE_ID DESC;
